world_frame: "world"
use_simulate: true
two_dimesion: true

## actuator params
actuator:
  endDeviation: 0.14
  initJointPoses:
    # - {q1: 0.1783, q2: 0.5602, q3: -0.2449, q4: -1.5819, q5: 1.9484, q6: 0.1644, q7: 0.6433}
    - {q1: 0.1683, q2: 0.4251, q3: -0.0850, q4: -1.4250, q5: -0.0042, q6: 1.2527, q7: 1.2268}
    - {q1: -0.6816, q2: 0.4251, q3: -0.0850, q4: -1.4250, q5: -0.0042, q6: 1.2527, q7: 1.2268}
    - {q1: -0.7438, q2: 0.7925, q3: -0.0850, q4: -1.5924, q5: -0.0112, q6: 0.7156, q7: 1.1889}

  # initJointPoses: 
  #   - {q1: -0.8073, q2: 0.6508, q3: -0.1780, q4: -1.4782, q5: 0.1215, q6: 1.0317, q7: 0.1414}   # used to calibrate VICON frame

simulate_actuator:
  initPos: {x: 0.4, y: -0.378, z: 0.065}
  pub_frequency: 100  # must faster than control_frequency

## env publisher params
env_publisher:
  publish_rate: 1
  publish_topic: "env_obstacles"
  VICON_topics:
    - "/vicon/shr_obs1/shr_obs1"
    - "/vicon/shr_obs2/shr_obs2"
    - "/ref1_1"
    - "/ref1_2"
    - "/ref2_1"


  VICON_transform: {x: 2.36, y: -0.47, z: -0.54, qx: 0, qy: 0, qz: -0.707, qw: 0.707} # VICON frame according to world frame
  obstacle_args:
    - {id: 0, type: "cube", size_x: 0.1, size_y: 0.1, size_z: 0.1, cor_x: 0.005, cor_y: 0.052, cor_z: -0.075}  
    - {id: 1, type: "cube", size_x: 0.1, size_y: 0.1, size_z: 0.1, cor_x: 0.018, cor_y: 0.065, cor_z: -0.055} 
    - {id: 2, type: "cube", size_x: 0.1, size_y: 0.1, size_z: 0.1, ref: 0, offset_x: 0, offset_y: -0.15, offset_z: 0}
    - {id: 3, type: "cube", size_x: 0.1, size_y: 0.1, size_z: 0.1, ref: 0, offset_x: 0, offset_y: -0.3, offset_z: 0}
    - {id: 4, type: "cube", size_x: 0.1, size_y: 0.1, size_z: 0.1, ref: 1, offset_x: 0, offset_y: -0.15, offset_z: 0}


## Global planner params
global_planner:
  publish_rate: 10
  publish_topic: "global_plan"
  obstacles_dilate: 0.015 
  smooth_step: 0.02  # actual distance between path points next to each other
  
RRT_planner:
    max_iter: 2000
    step_size: 0.02
    line_collision_check_resolution: 0.005
    check_goal_prob: 0.01
    search_space:
      x:
        - 0.37
        - 0.7
      y:
        - -0.45
        - 0.03
      z:
        - 0
        - 0

## Local planner params
MinimumLocalPlanner:
  opt_order: 4
  conti_order: 3
  order: 5
  optimizeT: false

## controller params
controller_type: "Shared"  # Admittance, Shared, Switching

controller:
  control_frequency: 10 # must slower than the frequency of sampling the sensor data

impedance_controller:
  M: 2
  C: 75

shared_controller:
  M: 2
  C: 75
  threshold_force: 3.3
  local_len: 50
  replan_len: 350
  replan_len_num: 20
  replan_freq: 1
  replan_timeout: 0.5
  replan_threshold: 0.05
  alpha: 100
  weight_r: 1       # 追踪机器人期望轨迹的误差权重为 weight_r*weight_tracking
  weight_h: 10
  weight_tracking: 1000
  load_traj: true
#  deviation: 0.05   # the max tolerated deviation from robot desired traj
