## env publisher params
env_publisher:
  publish_rate: 10
  publish_topic: "env_obstacles"
  VICON_topics:
    - "/vicon/Obstacle_1/Obstacle_1"
    - "/vicon/Obstacle_2/Obstacle_2"
    - "/vicon/Obstacle_3/Obstacle_3"
  obstacle_args:
    - {id: 0, type: "sphere", radius: 0.5}
    - {id: 1, type: "sphere", radius: 0.5}
    - {id: 2, type: "sphere", radius: 0.5}
