world_frame: "world"
use_simulate: true

## env publisher params
env_publisher:
  publish_rate: 10
  publish_topic: "env_obstacles"
  VICON_topics:
    - "/vicon/Obstacle_1/Obstacle_1"
    - "/vicon/Obstacle_2/Obstacle_2"
    - "/vicon/Obstacle_3/Obstacle_3"
    - "/vicon/Obstacle_4/Obstacle_4"
    - "/vicon/Obstacle_5/Obstacle_5"
    - "/vicon/Obstacle_6/Obstacle_6"
    - "/vicon/Obstacle_7/Obstacle_7"
    - "/vicon/Obstacle_8/Obstacle_8"
    - "/vicon/Obstacle_9/Obstacle_9"
  VICON_transform: {x: 1, y: 1, z: 1, qx: 0, qy: 0, qz: 0, qw: 1} # VICON frame according to world frame
  obstacle_args:
    - {id: 0, type: "cube", size_x: 1, size_y: 1, size_z: 1}
    - {id: 1, type: "cube", size_x: 2, size_y: 2, size_z: 2}
    - {id: 2, type: "cube", size_x: 0.8, size_y: 1, size_z: 0.7}
    - {id: 3, type: "cube", size_x: 2, size_y: 1, size_z: 1}
    - {id: 4, type: "cube", size_x: 1, size_y: 2, size_z: 1}
    - {id: 5, type: "cube", size_x: 1, size_y: 1, size_z: 2}
    - {id: 6, type: "sphere", radius: 1}
    - {id: 7, type: "sphere", radius: 1}
    - {id: 8, type: "sphere", radius: 1}

## Global planner params
global_planner:
  publish_rate: 10
  publish_topic: "global_plan"
  obstacles_dilate: 0.06
  smooth_step: 0.1

RRT_planner:
    max_iter: 10000
    step_size: 0.05
    line_collision_check_resolution: 0.05
    check_goal_prob: 0.01
    optimize_path: false
    search_space:
      x:
        - 0
        - 8
      y:
        - 0
        - 8
      z:
        - 0
        - 8

## Local planner params
MinimumLocalPlanner:
  opt_order: 4
  conti_order: 3
  order: 5
  optimizeT: true

## controller params
controller_type: "Shared"  # Admittance, Shared

controller:
  control_frequency: 10 # must slower than the frequency of sampling the sensor data

impedance_controller:
  M: 5
  C: 75

shared_controller:
  M: 5
  C: 75
  threshold_force: 3.7
  local_len: 50
  replan_len: 250
  replan_freq: 1
  alpha: 100
  weight_r: 1
  weight_h: 10
  weight_tracking: 10000
  load_traj: false


## actuator params
actuator:
  initJointPos: {q1: -1.0912, q2: -1.0999, q3: 1.16505, q4: 1.8945, q5: -1.2382, q6: -1.0227, q7: -0.2546}

simulate_actuator:
  initPos: {x: 0, y: 0, z: 0}
  pub_frequency: 100  # must faster than control_frequency