## env publisher params
env_publisher:
  publish_rate: 10
  publish_topic: "env_obstacles"
  VICON_topics:
    - "/vicon/Obstacle_1/Obstacle_1"
  obstacle_args:
    - {id: 0, type: "sphere", radius: 0.5}
